# Generated by Django 6.0 on 2025-12-05 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="employee",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to employee record if applicable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_account",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                help_text="Company this user belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="accounts.company",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("company", "email"), name="unique_email_per_company"
            ),
        ),
    ]
