# Generated by Django 6.0 on 2025-12-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="attendance_exceptions_alerts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="automated_onboarding_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="disciplinary_alerts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="leave_request_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
