# Generated by Django 6.0 on 2025-12-15 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("employees", "0002_employee_employees_e_company_8e5f43_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BenefitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("insurance", "Insurance"),
                            ("allowance", "Allowance"),
                            ("loan", "Loan / Advance"),
                            ("retirement", "Retirement / Pension"),
                            ("perk", "Perk / Subscription"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "default_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Monetary value or Premium cost",
                        max_digits=12,
                    ),
                ),
                ("is_taxable", models.BooleanField(default=False)),
                (
                    "provider_name",
                    models.CharField(
                        blank=True, help_text="e.g. Jubilee Insurance", max_length=255
                    ),
                ),
                ("provider_contact", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefit_types",
                        to="accounts.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "coverage_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Specific value for this employee",
                        max_digits=12,
                    ),
                ),
                (
                    "employee_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Deducted from salary",
                        max_digits=12,
                    ),
                ),
                (
                    "employer_contribution",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending Approval"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "dependents_covered",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of family members covered",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "benefit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="benefits.benefittype",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
