# Generated by Django 6.0 on 2026-01-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefittype',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='employeebenefit',
            options={'ordering': ['-created_at']},
        ),
    ]
