# Generated by Django 6.0 on 2026-01-20 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_forms', '0001_initial'),
        ('employees', '0002_employee_employees_e_company_8e5f43_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formsubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='employees.employee'),
        ),
    ]
