import React from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Link, useNavigate } from 'react-router-dom';
import { useDispatch } from 'react-redux';
import { useLoginMutation } from '../../store/api'; // We need to create this endpoint
import { setCredentials } from './authSlice';
import { Button } from '../../components/ui/Button';
import { Input } from '../../components/ui/Input';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '../../components/ui/Card';
import { AlertCircle } from 'lucide-react';
import toast from 'react-hot-toast';

// Validation Schema
const loginSchema = z.object({
    username: z.string().min(1, 'Username is required'),
    password: z.string().min(1, 'Password is required'),
});

const LoginPage = () => {
    const navigate = useNavigate();
    const dispatch = useDispatch();

    // This hook will be generated by RTK Query, but we haven't defined the endpoints yet.
    // I'll define the endpoints in the next step.
    // For now, I'll assume it exists to structure the page.
    const [login, { isLoading, error }] = useLoginMutation();

    const { register, handleSubmit, formState: { errors } } = useForm({
        resolver: zodResolver(loginSchema),
    });

    const onSubmit = async (data) => {
        try {
            const result = await login(data).unwrap();
            dispatch(setCredentials({
                user: result.user,
                token: result.tokens.access
            }));
            toast.success('Welcome back!');
            navigate('/dashboard');
        } catch (err) {
            toast.error(err?.data?.error || 'Login failed. Please check your credentials.');
            console.error('Login failed:', err);
        }
    };

    return (
        <div className="animate-fade-in">
            <div className="text-center mb-8 lg:hidden">
                <h2 className="text-3xl font-bold text-gray-900">LahHR</h2>
                <p className="mt-2 text-gray-600">Sign in to your account</p>
            </div>

            <Card className="border-none shadow-none bg-transparent lg:bg-white lg:border lg:shadow-sm">
                <CardHeader className="text-center lg:text-left px-0 lg:px-6">
                    <CardTitle className="text-2xl lg:text-3xl">Welcome back</CardTitle>
                    <CardDescription className="text-base mt-2">
                        Enter your credentials to access your workspace
                    </CardDescription>
                </CardHeader>

                <CardContent className="px-0 lg:px-6">
                    {error && (
                        <div className="mb-6 p-4 rounded-lg bg-error-50 border border-error-200 flex items-start gap-3">
                            <AlertCircle className="h-5 w-5 text-error-600 mt-0.5 flex-shrink-0" />
                            <div className="text-sm text-error-700">
                                <p className="font-medium">Authentication failed</p>
                                <p>{error?.data?.error || 'Please check your credentials and try again.'}</p>
                            </div>
                        </div>
                    )}

                    <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
                        <Input
                            label="Username"
                            type="text"
                            placeholder="Enter your username"
                            error={errors.username?.message}
                            {...register('username')}
                        />

                        <div className="space-y-1">
                            <div className="flex items-center justify-between">
                                <Input
                                    label="Password"
                                    type="password"
                                    placeholder="••••••••"
                                    error={errors.password?.message}
                                    {...register('password')}
                                />
                            </div>
                            <div className="flex justify-end">
                                <Link
                                    to="/forgot-password"
                                    className="text-sm font-medium text-primary-600 hover:text-primary-700 hover:underline"
                                >
                                    Forgot password?
                                </Link>
                            </div>
                        </div>

                        <Button
                            type="submit"
                            fullWidth
                            size="lg"
                            isLoading={isLoading}
                            className="mt-6"
                        >
                            Sign in
                        </Button>
                    </form>
                </CardContent>

                <CardFooter className="flex justify-center px-0 lg:px-6">
                    <p className="text-sm text-gray-600">
                        Don't have an account?{' '}
                        <Link to="/register" className="font-medium text-primary-600 hover:text-primary-700 hover:underline">
                            Create a company
                        </Link>
                    </p>
                </CardFooter>
            </Card>
        </div>
    );
};

export default LoginPage;
