import React from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Link, useNavigate } from 'react-router-dom';
import { useDispatch } from 'react-redux';
import { useLoginMutation } from '../../store/api'; // We need to create this endpoint
import { setCredentials } from './authSlice';
import { Button } from '../../components/ui/Button';
import { Input } from '../../components/ui/Input';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '../../components/ui/Card';
import { AlertCircle } from 'lucide-react';

// Validation Schema
const loginSchema = z.object({
    username: z.string().min(1, 'Username is required'),
    password: z.string().min(1, 'Password is required'),
});

const LoginPage = () => {
    const navigate = useNavigate();
    const dispatch = useDispatch();

    // This hook will be generated by RTK Query, but we haven't defined the endpoints yet.
    // I'll define the endpoints in the next step.
    // For now, I'll assume it exists to structure the page.
    const [login, { isLoading, error }] = useLoginMutation();

    const [show2FA, setShow2FA] = React.useState(false);
    const [loginData, setLoginData] = React.useState(null);

    const { register, handleSubmit, formState: { errors }, watch } = useForm({
        resolver: zodResolver(loginSchema),
    });

    const onSubmit = async (data) => {
        try {
            const result = await login(show2FA ? { ...loginData, otp_code: data.otp_code } : data).unwrap();

            if (result.two_factor_required) {
                setShow2FA(true);
                setLoginData(data);
                return;
            }

            dispatch(setCredentials({
                user: result.user,
                token: result.tokens.access,
                refresh: result.tokens.refresh
            }));
            navigate('/dashboard');
        } catch (err) {
            console.error('Login failed:', err);
        }
    };

    return (
        <div className="animate-fade-in">
            <div className="text-center mb-8 lg:hidden">
                <h2 className="text-3xl font-bold text-gray-900">Lifeline</h2>
                <p className="mt-2 text-gray-600">Sign in to your account</p>
            </div>

            <Card className="border-none shadow-none bg-transparent lg:bg-white lg:border lg:shadow-sm">
                <CardHeader className="text-center lg:text-left px-0 lg:px-6">
                    <CardTitle className="text-2xl lg:text-3xl">Welcome back</CardTitle>
                    <CardDescription className="text-base mt-2">
                        Enter your credentials to access your workspace
                    </CardDescription>
                </CardHeader>

                <CardContent className="px-0 lg:px-6">
                    {error && (
                        <div className="mb-6 p-4 rounded-lg bg-error-50 border border-error-200 flex items-start gap-3">
                            <AlertCircle className="h-5 w-5 text-error-600 mt-0.5 flex-shrink-0" />
                            <div className="text-sm text-error-700">
                                <p className="font-medium">Authentication failed</p>
                                <p>{error?.data?.error || 'Please check your credentials and try again.'}</p>
                            </div>
                        </div>
                    )}

                    <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
                        {!show2FA ? (
                            <>
                                <Input
                                    label="Username"
                                    type="text"
                                    placeholder="Enter your username"
                                    error={errors.username?.message}
                                    {...register('username')}
                                />

                                <div className="space-y-1">
                                    <div className="flex items-center justify-between">
                                        <Input
                                            label="Password"
                                            type="password"
                                            placeholder="••••••••"
                                            error={errors.password?.message}
                                            {...register('password')}
                                        />
                                    </div>
                                    <div className="flex justify-end">
                                        <Link
                                            to="/forgot-password"
                                            className="text-sm font-medium text-primary-600 hover:text-primary-700 hover:underline"
                                        >
                                            Forgot password?
                                        </Link>
                                    </div>
                                </div>
                            </>
                        ) : (
                            <div className="animate-in slide-in-from-bottom-2 duration-300">
                                <Input
                                    label="Two-Factor Code"
                                    type="text"
                                    placeholder="000000"
                                    autoFocus
                                    maxLength={6}
                                    error={errors.otp_code?.message}
                                    {...register('otp_code')}
                                    className="text-center text-3xl tracking-[0.5em] font-bold h-16"
                                />
                                <p className="text-sm text-slate-500 mt-4 text-center">
                                    Open your authenticator app and enter the 6-digit verification code.
                                </p>
                            </div>
                        )}

                        <Button
                            type="submit"
                            fullWidth
                            size="lg"
                            isLoading={isLoading}
                            className="mt-6"
                        >
                            {show2FA ? 'Verify & Sign in' : 'Sign in'}
                        </Button>

                        {show2FA && (
                            <button
                                type="button"
                                onClick={() => setShow2FA(false)}
                                className="w-full text-sm text-slate-500 hover:text-slate-900 font-medium py-2"
                            >
                                Back to login
                            </button>
                        )}
                    </form>
                </CardContent>

                <CardFooter className="flex justify-center px-0 lg:px-6">
                    <p className="text-sm text-gray-600">
                        Don't have an account?{' '}
                        <Link to="/register" className="font-medium text-primary-600 hover:text-primary-700 hover:underline">
                            Create a company
                        </Link>
                    </p>
                </CardFooter>
            </Card>
        </div>
    );
};

export default LoginPage;
