# Generated by Django 6.0 on 2025-12-16 08:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("employees", "0002_employee_employees_e_company_8e5f43_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("registered", "Registered"),
                            ("waitlisted", "Waitlisted"),
                            ("confirmed", "Confirmed"),
                            ("attended", "Attended"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("no_show", "No Show"),
                            ("cancelled", "Cancelled"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("requires_approval", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True)),
                ("attendance_marked", models.BooleanField(default=False)),
                ("attendance_date", models.DateTimeField(blank=True, null=True)),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assessment_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "passing_score_required",
                    models.DecimalField(
                        decimal_places=2,
                        default=70,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("assessment_attempts", models.IntegerField(default=0)),
                ("certificate_issued", models.BooleanField(default=False)),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("certificate_issued_at", models.DateTimeField(blank=True, null=True)),
                ("certificate_expires_at", models.DateField(blank=True, null=True)),
                (
                    "feedback_text",
                    models.TextField(blank=True, help_text="Employee feedback"),
                ),
                (
                    "feedback_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("feedback_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_enrollments",
                        to="employees.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_enrollments",
                        to="employees.employee",
                    ),
                ),
                (
                    "enrolled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments_created",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("enrollment_confirmation", "Enrollment Confirmation"),
                            ("session_reminder", "Session Reminder"),
                            (
                                "completion_congratulations",
                                "Completion Congratulations",
                            ),
                            ("certificate_issued", "Certificate Issued"),
                            ("assessment_due", "Assessment Due"),
                            ("compliance_warning", "Compliance Warning"),
                            ("session_cancelled", "Session Cancelled"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("sent_via", models.CharField(default="email", max_length=50)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_notifications",
                        to="employees.employee",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="training.trainingenrollment",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique program identifier (e.g., TRN-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "objectives",
                    models.TextField(help_text="Learning objectives and outcomes"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Skills"),
                            ("soft_skills", "Soft Skills"),
                            ("compliance", "Compliance & Regulations"),
                            ("leadership", "Leadership & Management"),
                            ("safety", "Health & Safety"),
                            ("onboarding", "Onboarding"),
                            ("product", "Product Knowledge"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Training provider or department", max_length=255
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False, help_text="Required for all employees"
                    ),
                ),
                (
                    "target_departments",
                    models.JSONField(
                        blank=True, default=list, help_text="List of department names"
                    ),
                ),
                (
                    "target_roles",
                    models.JSONField(
                        blank=True, default=list, help_text="List of role names"
                    ),
                ),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.5)],
                    ),
                ),
                (
                    "estimated_effort_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected self-study time",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "validity_period_months",
                    models.IntegerField(
                        blank=True,
                        help_text="Recertification period in months",
                        null=True,
                    ),
                ),
                (
                    "materials_url",
                    models.URLField(blank=True, help_text="Link to training materials"),
                ),
                ("external_platform_url", models.URLField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low Priority"),
                            ("medium", "Medium Priority"),
                            ("high", "High Priority"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_programs",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_programs",
                        to="employees.employee",
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="required_for",
                        to="training.trainingprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingComplianceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applies_to_departments", models.JSONField(blank=True, default=list)),
                ("applies_to_roles", models.JSONField(blank=True, default=list)),
                ("applies_to_all", models.BooleanField(default=False)),
                (
                    "required_by_date",
                    models.DateField(
                        blank=True, help_text="Deadline for completion", null=True
                    ),
                ),
                (
                    "recurrence_months",
                    models.IntegerField(
                        blank=True,
                        help_text="Recurring training every X months",
                        null=True,
                    ),
                ),
                (
                    "grace_period_days",
                    models.IntegerField(
                        default=0, help_text="Days after due date before non-compliance"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_rules",
                        to="accounts.company",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_rules",
                        to="training.trainingprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("pre_test", "Pre-Assessment"),
                            ("post_test", "Post-Assessment"),
                            ("quiz", "Quiz"),
                            ("practical", "Practical Evaluation"),
                            ("survey", "Survey"),
                        ],
                        default="post_test",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "passing_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=70,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.IntegerField(
                        blank=True, help_text="Time limit in minutes", null=True
                    ),
                ),
                ("total_questions", models.IntegerField(default=0)),
                (
                    "questions_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Assessment questions structure",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("available_from", models.DateTimeField(blank=True, null=True)),
                ("available_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="training.trainingprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["program", "assessment_type"],
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_code",
                    models.CharField(
                        help_text="Unique session identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "title_override",
                    models.CharField(
                        blank=True,
                        help_text="Custom session title if different",
                        max_length=255,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("in_person", "In-Person"),
                            ("virtual", "Virtual/Online"),
                            ("hybrid", "Hybrid"),
                            ("self_paced", "Self-Paced"),
                        ],
                        default="in_person",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location or meeting link",
                        max_length=255,
                    ),
                ),
                ("external_facilitator", models.CharField(blank=True, max_length=255)),
                (
                    "min_participants",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        default=20,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("allow_waitlist", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("open_enrollment", "Open for Enrollment"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True)),
                ("session_materials_url", models.URLField(blank=True)),
                ("meeting_link", models.URLField(blank=True)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("completion_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facilitator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facilitated_sessions",
                        to="employees.employee",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="training.trainingprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="trainingenrollment",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="training.trainingsession",
            ),
        ),
        migrations.CreateModel(
            name="TrainingCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_number", models.CharField(max_length=100, unique=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("employee_name", models.CharField(max_length=255)),
                ("program_name", models.CharField(max_length=255)),
                ("completion_date", models.DateField()),
                (
                    "certificate_file_url",
                    models.URLField(
                        blank=True, help_text="URL to generated PDF certificate"
                    ),
                ),
                ("certificate_file_path", models.CharField(blank=True, max_length=500)),
                ("verification_code", models.CharField(max_length=50, unique=True)),
                ("is_revoked", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True)),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="training.trainingenrollment",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["certificate_number"],
                        name="training_tr_certifi_50d88d_idx",
                    ),
                    models.Index(
                        fields=["verification_code"],
                        name="training_tr_verific_3e26c8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AssessmentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.IntegerField(default=1)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                (
                    "answers_data",
                    models.JSONField(default=dict, help_text="Student answers"),
                ),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("grading_notes", models.TextField(blank=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="training.assessment",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_assessments",
                        to="employees.employee",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_results",
                        to="training.trainingenrollment",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["enrollment", "assessment"],
                        name="training_as_enrollm_5dd4f0_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="trainingprogram",
            index=models.Index(
                fields=["company", "is_active"], name="training_tr_company_1febc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingprogram",
            index=models.Index(
                fields=["is_mandatory"], name="training_tr_is_mand_fbcede_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingprogram",
            index=models.Index(
                fields=["category"], name="training_tr_categor_ad0138_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingsession",
            index=models.Index(
                fields=["program", "status"], name="training_tr_program_252c3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingsession",
            index=models.Index(
                fields=["start_date", "end_date"], name="training_tr_start_d_c9a0da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingsession",
            index=models.Index(fields=["status"], name="training_tr_status_f37730_idx"),
        ),
        migrations.AddIndex(
            model_name="trainingenrollment",
            index=models.Index(
                fields=["employee", "status"], name="training_tr_employe_f3c62b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingenrollment",
            index=models.Index(
                fields=["session", "status"], name="training_tr_session_42a99e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingenrollment",
            index=models.Index(fields=["status"], name="training_tr_status_14edf1_idx"),
        ),
        migrations.AddIndex(
            model_name="trainingenrollment",
            index=models.Index(
                fields=["completed_at"], name="training_tr_complet_a84c38_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trainingenrollment",
            unique_together={("session", "employee")},
        ),
    ]
