# Generated by Django 6.0 on 2025-12-15 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("employees", "0002_employee_employees_e_company_8e5f43_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "provider",
                    models.CharField(
                        help_text="e.g. Udemy, Internal HR, Google", max_length=255
                    ),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal Workshop"),
                            ("external", "External Seminar"),
                            ("online", "Online Course"),
                            ("certification", "Certification Program"),
                        ],
                        default="internal",
                        max_length=50,
                    ),
                ),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=2, help_text="Total hours", max_digits=6
                    ),
                ),
                (
                    "cost_per_person",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("website_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="accounts.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instructor", models.CharField(blank=True, max_length=255)),
                (
                    "location",
                    models.CharField(
                        help_text="Physical room or Meeting Link", max_length=255
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("capacity", models.IntegerField(default=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="training.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("attended", "Attended"),
                            ("no_show", "No Show"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "score",
                    models.IntegerField(
                        blank=True, help_text="Percentage or Grade", null=True
                    ),
                ),
                (
                    "certificate_url",
                    models.URLField(blank=True, help_text="Link to stored certificate"),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Employee feedback on course"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_enrollments",
                        to="employees.employee",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="training.trainingsession",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "employee")},
            },
        ),
    ]
