# Generated by Django 6.0 on 2026-01-20 10:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_user_data_consent_user_data_consent_at_and_more'),
        ('employees', '0002_employee_employees_e_company_8e5f43_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCCPayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('UAE', 'United Arab Emirates'), ('KSA', 'Saudi Arabia'), ('QAT', 'Qatar'), ('OMN', 'Oman'), ('KWT', 'Kuwait'), ('BHR', 'Bahrain')], max_length=3)),
                ('social_insurance_enabled', models.BooleanField(default=True)),
                ('citizen_contribution_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('employer_contribution_rate', models.DecimalField(decimal_places=2, default=Decimal('12.50'), max_digits=5)),
                ('gratuity_scheme', models.CharField(default='Standard Labor Law', max_length=50)),
                ('base_salary_type', models.CharField(choices=[('basic', 'Basic Only'), ('gross', 'Gross Salary')], default='basic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gcc_settings', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='GratuityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('total_years_service', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('accrued_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_salary_base', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('accruing', 'Accruing'), ('paid', 'Paid')], default='accruing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratuity_records', to='employees.employee')),
            ],
        ),
    ]
