# Generated by Django 6.0.1 on 2026-01-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leaverequest_reliever'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='reliever_name',
            field=models.CharField(blank=True, help_text='Name of the person covering (if not an employee)', max_length=255),
        ),
    ]
