# Generated by Django 6.0 on 2026-01-20 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_user_data_consent_user_data_consent_at_and_more'),
        ('employees', '0002_employee_employees_e_company_8e5f43_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('survey_type', models.CharField(choices=[('pulse', 'Pulse Survey'), ('enps', 'eNPS'), ('satisfaction', 'Satisfaction Survey'), ('custom', 'Custom Survey')], default='pulse', max_length=20)),
                ('questions_config', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_data', models.JSONField(default=dict)),
                ('anonymous_id', models.UUIDField(blank=True, help_text='Used for tracking unique responses in anonymous surveys', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='employees.employee')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey')),
            ],
            options={
                'unique_together': {('survey', 'employee')},
            },
        ),
    ]
