# Generated by Django 6.0 on 2026-01-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyresponse',
            options={'ordering': ['-submitted_at']},
        ),
    ]
