# Generated by Django 6.0 on 2025-12-10 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("employees", "0002_employee_employees_e_company_8e5f43_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendancePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_start_time", models.TimeField(default="09:00")),
                ("work_end_time", models.TimeField(default="17:00")),
                (
                    "break_duration_minutes",
                    models.IntegerField(default=60, help_text="Lunch break in minutes"),
                ),
                (
                    "grace_period_minutes",
                    models.IntegerField(
                        default=15, help_text="Grace period before marking late"
                    ),
                ),
                (
                    "late_arrival_threshold",
                    models.IntegerField(
                        default=3, help_text="Late arrivals per month before penalty"
                    ),
                ),
                (
                    "overtime_rate_multiplier",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=3),
                ),
                ("overtime_auto_approve", models.BooleanField(default=False)),
                (
                    "working_days",
                    models.CharField(
                        default="Monday,Tuesday,Wednesday,Thursday,Friday",
                        help_text="Comma-separated working days",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_policy",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Policy",
                "verbose_name_plural": "Attendance Policies",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("on_leave", "On Leave"),
                            ("holiday", "Public Holiday"),
                            ("weekend", "Weekend"),
                        ],
                        default="absent",
                        max_length=20,
                    ),
                ),
                ("clock_in", models.DateTimeField(blank=True, null=True)),
                ("clock_out", models.DateTimeField(blank=True, null=True)),
                ("is_late", models.BooleanField(default=False)),
                ("late_by_minutes", models.IntegerField(default=0)),
                (
                    "hours_worked",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_attendances",
                        to="employees.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendances",
                "ordering": ["-date", "employee"],
                "indexes": [
                    models.Index(
                        fields=["employee", "date"],
                        name="attendance__employe_08d913_idx",
                    ),
                    models.Index(
                        fields=["date", "status"], name="attendance__date_3889e6_idx"
                    ),
                ],
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("total_working_days", models.IntegerField(default=0)),
                ("days_present", models.IntegerField(default=0)),
                ("days_absent", models.IntegerField(default=0)),
                ("days_on_leave", models.IntegerField(default=0)),
                ("late_arrivals", models.IntegerField(default=0)),
                (
                    "total_hours_worked",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_overtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "attendance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of days present",
                        max_digits=5,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_reports",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Report",
                "verbose_name_plural": "Attendance Reports",
                "ordering": ["-year", "-month", "employee"],
                "unique_together": {("employee", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="OvertimeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "hours_requested",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_overtime",
                        to="employees.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtime_requests",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overtime Request",
                "verbose_name_plural": "Overtime Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "status"],
                        name="attendance__employe_c62e32_idx",
                    ),
                    models.Index(fields=["date"], name="attendance__date_e94e22_idx"),
                ],
            },
        ),
    ]
