# Generated by Django 6.0.1 on 2026-01-19 08:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_attendance_exceptions_alerts_and_more'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='clock_in_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_in_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='device_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='enable_geofencing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='enable_qr_clock_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='require_photo_clock_in',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_meters', models.IntegerField(default=100, help_text='Allowed radius in meters')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_locations', to='accounts.company')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.worklocation'),
        ),
    ]
