# Generated by Django 6.0 on 2025-12-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offboarding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resignation",
            name="access_revoked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resignation",
            name="assets_returned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resignation",
            name="email_disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resignation",
            name="exit_interview_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resignation",
            name="handover_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resignation",
            name="settlement_completed",
            field=models.BooleanField(default=False),
        ),
    ]
