# Generated by Django 6.0 on 2025-12-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offboarding", "0002_resignation_access_revoked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resignation",
            name="id_badge_returned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resignation",
            name="keys_returned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resignation",
            name="laptop_returned",
            field=models.BooleanField(default=False),
        ),
    ]
