# Generated by Django 6.0 on 2025-12-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_employees_e_company_8e5f43_idx_and_more'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performancereview',
            unique_together={('cycle', 'employee', 'reviewer')},
        ),
        migrations.AddField(
            model_name='performancereview',
            name='is_360_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='review_type',
            field=models.CharField(choices=[('self', 'Self Review'), ('manager', 'Manager Review'), ('peer', 'Peer Review'), ('subordinate', 'Subordinate Review')], default='manager', max_length=20),
        ),
    ]
