# Generated by Django 6.0 on 2026-01-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_expiry_date_document_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='Size in bytes'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='Size in bytes'),
        ),
    ]
