# Generated by Django 6.0 on 2025-12-08 07:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("salary_advance", "Salary Advance"),
                            ("personal_loan", "Personal Loan"),
                            ("emergency_loan", "Emergency Loan"),
                            ("other", "Other"),
                        ],
                        default="salary_advance",
                        max_length=20,
                    ),
                ),
                (
                    "loan_purpose",
                    models.TextField(blank=True, help_text="Purpose of the loan"),
                ),
                ("disbursement_date", models.DateField(blank=True, null=True)),
                (
                    "repayment_period_months",
                    models.IntegerField(
                        default=1, help_text="Number of months to repay"
                    ),
                ),
                (
                    "monthly_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monthly deduction amount",
                        max_digits=12,
                    ),
                ),
                (
                    "total_repaid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Remaining balance",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("defaulted", "Defaulted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField(help_text="Month (1-12)")),
                ("year", models.IntegerField(help_text="Year (e.g., 2024)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("processing", "Processing"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "total_gross",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total gross salary for all employees",
                        max_digits=15,
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total deductions for all employees",
                        max_digits=15,
                    ),
                ),
                (
                    "total_net",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total net salary for all employees",
                        max_digits=15,
                    ),
                ),
                (
                    "employee_count",
                    models.IntegerField(
                        default=0, help_text="Number of employees in this payroll"
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_runs",
                        to="accounts.company",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_payrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Run",
                "verbose_name_plural": "Payroll Runs",
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "allowances",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "bonuses",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "paye_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Pay As You Earn tax (Uganda)",
                        max_digits=12,
                    ),
                ),
                (
                    "nssf_employee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="NSSF employee contribution (10%)",
                        max_digits=12,
                    ),
                ),
                (
                    "nssf_employer",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="NSSF employer contribution (10%)",
                        max_digits=12,
                    ),
                ),
                (
                    "loan_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Loan/advance repayment",
                        max_digits=12,
                    ),
                ),
                (
                    "advance_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Salary advance deduction",
                        max_digits=12,
                    ),
                ),
                (
                    "other_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Other deductions (insurance, etc.)",
                        max_digits=12,
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("net_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("mobile_money", "Mobile Money"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                (
                    "payslip_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF payslip",
                        null=True,
                        upload_to="payslips/",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="employees.employee",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="payroll.payrollrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payslip",
                "verbose_name_plural": "Payslips",
                "ordering": ["payroll_run", "employee__employee_number"],
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="When this salary structure becomes effective"
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Basic monthly salary (UGX)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "housing_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Housing allowance",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "transport_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Transport allowance",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "medical_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Medical allowance",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "lunch_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Lunch allowance",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "other_allowances",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Other allowances (airtime, etc.)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Total gross salary (auto-calculated)",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this salary change"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_salary_structures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_structures",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Structure",
                "verbose_name_plural": "Salary Structures",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(
                fields=("company", "month", "year"),
                name="unique_payroll_run_per_company_month_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="payslip",
            constraint=models.UniqueConstraint(
                fields=("payroll_run", "employee"),
                name="unique_payslip_per_payroll_employee",
            ),
        ),
        migrations.AddConstraint(
            model_name="salarystructure",
            constraint=models.UniqueConstraint(
                fields=("employee", "effective_date"),
                name="unique_salary_structure_per_employee_date",
            ),
        ),
    ]
