# Generated by Django 6.0 on 2025-12-09 11:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("employees", "0001_initial"),
        ("payroll", "0003_add_is_active_to_salarystructure"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("salary_advance", "Salary Advance"),
                            ("personal_loan", "Personal Loan"),
                            ("emergency_loan", "Emergency Loan"),
                            ("other", "Other"),
                        ],
                        default="salary_advance",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("loan_purpose", models.TextField(blank=True)),
                ("repayment_period_months", models.PositiveIntegerField(default=1)),
                (
                    "monthly_deduction",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=15
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("defaulted", "Defaulted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "amount_repaid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=15
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Salary Advance",
                "verbose_name_plural": "Salary Advances",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="TaxSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("UG", "Uganda"), ("KE", "Kenya"), ("TZ", "Tanzania")],
                        default="UG",
                        max_length=2,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("UGX", "Uganda Shilling"),
                            ("KES", "Kenya Shilling"),
                            ("TZS", "Tanzania Shilling"),
                        ],
                        default="UGX",
                        max_length=3,
                    ),
                ),
                (
                    "personal_relief",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("240000.00"), max_digits=15
                    ),
                ),
                (
                    "insurance_relief",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("50000.00"), max_digits=15
                    ),
                ),
                (
                    "pension_fund_relief",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("200000.00"), max_digits=15
                    ),
                ),
                (
                    "nssf_employee_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=5
                    ),
                ),
                (
                    "nssf_employer_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=5
                    ),
                ),
                (
                    "nssf_ceiling",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100000.00"), max_digits=15
                    ),
                ),
                ("local_service_tax_enabled", models.BooleanField(default=True)),
                (
                    "local_service_tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=5
                    ),
                ),
                ("tax_year", models.PositiveIntegerField(default=2024)),
                ("effective_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tax Settings",
                "verbose_name_plural": "Tax Settings",
                "ordering": ["-tax_year"],
            },
        ),
        migrations.RemoveField(
            model_name="loan",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="employee",
        ),
        migrations.AlterModelOptions(
            name="payslip",
            options={
                "ordering": [
                    "-payroll_run__year",
                    "-payroll_run__month",
                    "employee__first_name",
                    "employee__last_name",
                ],
                "verbose_name": "Payslip",
                "verbose_name_plural": "Payslips",
            },
        ),
        migrations.RemoveConstraint(
            model_name="payrollrun",
            name="unique_payroll_run_per_company_month_year",
        ),
        migrations.RemoveConstraint(
            model_name="payslip",
            name="unique_payslip_per_payroll_employee",
        ),
        migrations.RemoveConstraint(
            model_name="salarystructure",
            name="unique_salary_structure_per_employee_date",
        ),
        migrations.AlterUniqueTogether(
            name="payrollrun",
            unique_together={("company", "month", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="payslip",
            unique_together={("payroll_run", "employee")},
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="total_nssf_employee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="total_nssf_employer",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="total_paye",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="payslip",
            name="bonus",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payslip",
            name="housing_allowance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="lunch_allowance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="medical_allowance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="other_allowances",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="transport_allowance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_payrolls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="month",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_payrolls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="total_deductions",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="total_gross",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="total_net",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="year",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="advance_deduction",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="basic_salary",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="gross_salary",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="loan_deduction",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="net_salary",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="nssf_employee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="nssf_employer",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="other_deductions",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="paye_tax",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("bank", "Bank Transfer"),
                    ("cash", "Cash"),
                    ("mobile", "Mobile Money"),
                ],
                default="bank",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="total_deductions",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="salarystructure",
            name="basic_salary",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="salarystructure",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_structures",
                to="accounts.company",
            ),
        ),
        migrations.AlterField(
            model_name="salarystructure",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="salarystructure",
            name="effective_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="salarystructure",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_structure",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="salarystructure",
            name="gross_salary",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name="salarystructure",
            name="housing_allowance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="salarystructure",
            name="lunch_allowance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="salarystructure",
            name="medical_allowance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="salarystructure",
            name="other_allowances",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="salarystructure",
            name="transport_allowance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="salaryadvance",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_advances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salaryadvance",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_advances",
                to="accounts.company",
            ),
        ),
        migrations.AddField(
            model_name="salaryadvance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salaryadvance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_advances",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="taxsettings",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_settings",
                to="accounts.company",
            ),
        ),
        migrations.AddField(
            model_name="taxsettings",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Loan",
        ),
        migrations.RemoveField(
            model_name="salarystructure",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="payrollrun",
            name="employee_count",
        ),
        migrations.RemoveField(
            model_name="payrollrun",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="payrollrun",
            name="paid_at",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="allowances",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="bonuses",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="payslip_file",
        ),
    ]
