# Generated by Django 6.0 on 2025-12-10 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("payroll", "0004_salaryadvance_taxsettings_remove_loan_approved_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(
                fields=["company", "status"], name="payroll_pay_company_32e802_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(
                fields=["company", "year", "month"],
                name="payroll_pay_company_790f46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(
                fields=["company", "-year", "-month"],
                name="payroll_pay_company_9edb80_idx",
            ),
        ),
    ]
