# Generated by Django 6.0 on 2025-12-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0005_payrollrun_payroll_pay_company_32e802_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollrun",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
