# Generated by Django 6.0 on 2025-12-19 14:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_attendance_exceptions_alerts_and_more'),
        ('employees', '0002_employee_employees_e_company_8e5f43_idx_and_more'),
        ('payroll', '0006_payrollrun_description_payrollrun_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyWageAccessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable EWA for this company')),
                ('min_tenure_months', models.PositiveIntegerField(default=3, help_text='Minimum months of employment required')),
                ('min_salary_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum monthly salary to be eligible', max_digits=15)),
                ('max_percentage_of_salary', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Maximum % of monthly salary that can be advanced', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum fixed amount (optional cap)', max_digits=15, null=True)),
                ('max_requests_per_month', models.PositiveIntegerField(default=2, help_text='Maximum number of EWA requests per month')),
                ('min_days_between_requests', models.PositiveIntegerField(default=7, help_text='Minimum days between consecutive requests')),
                ('auto_approve_enabled', models.BooleanField(default=False, help_text='Auto-approve requests below threshold')),
                ('auto_approve_threshold', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), help_text='Auto-approve requests below this amount', max_digits=15)),
                ('default_repayment_months', models.PositiveIntegerField(default=1, help_text='Default repayment period in months')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ewa_config', to='accounts.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Early Wage Access Configuration',
                'verbose_name_plural': 'Early Wage Access Configurations',
            },
        ),
        migrations.CreateModel(
            name='WageAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('ewa', 'Early Wage Access'), ('emergency', 'Emergency Advance'), ('standard', 'Standard Loan')], default='ewa', max_length=20)),
                ('earned_to_date', models.DecimalField(decimal_places=2, help_text='Amount earned up to request date', max_digits=15)),
                ('days_worked', models.PositiveIntegerField(help_text='Days worked in current month')),
                ('working_days_in_month', models.PositiveIntegerField(help_text='Total working days in month')),
                ('is_eligible', models.BooleanField(default=False)),
                ('eligibility_notes', models.TextField(blank=True)),
                ('auto_approved', models.BooleanField(default=False)),
                ('disbursed', models.BooleanField(default=False)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursement_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash')], default='mobile_money', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ewa_requests', to='accounts.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ewa_requests', to='employees.employee')),
                ('salary_advance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ewa_details', to='payroll.salaryadvance')),
            ],
            options={
                'verbose_name': 'Wage Access Request',
                'verbose_name_plural': 'Wage Access Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'employee', '-created_at'], name='payroll_wag_company_7c24fa_idx'), models.Index(fields=['company', 'request_type', '-created_at'], name='payroll_wag_company_c44b0b_idx')],
            },
        ),
    ]
