# Generated by Django 6.0 on 2025-12-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_earlywageaccessconfig_wageaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='payslips/'),
        ),
    ]
