# Generated by Django 6.0 on 2025-12-05 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Department name (e.g., IT, HR, Finance)",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Department code (e.g., IT, HR, FIN)",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this department belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_number",
                    models.CharField(
                        help_text="Unique employee ID (e.g., EMP001, EMP002)",
                        max_length=50,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "national_id",
                    models.CharField(help_text="National ID number", max_length=50),
                ),
                ("passport_number", models.CharField(blank=True, max_length=50)),
                (
                    "tin_number",
                    models.CharField(
                        blank=True, help_text="TIN for tax", max_length=50
                    ),
                ),
                (
                    "nssf_number",
                    models.CharField(
                        blank=True, help_text="NSSF number (Uganda)", max_length=50
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("personal_email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "district",
                    models.CharField(
                        blank=True, help_text="District (for Uganda)", max_length=100
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="employee_photos/"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        help_text="Job title (e.g., Software Engineer)", max_length=255
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("intern", "Intern"),
                            ("casual", "Casual"),
                        ],
                        default="full_time",
                        max_length=50,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_leave", "On Leave"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                            ("resigned", "Resigned"),
                        ],
                        default="active",
                        max_length=50,
                    ),
                ),
                (
                    "join_date",
                    models.DateField(help_text="Date employee joined the company"),
                ),
                ("probation_end_date", models.DateField(blank=True, null=True)),
                ("confirmation_date", models.DateField(blank=True, null=True)),
                ("resignation_date", models.DateField(blank=True, null=True)),
                ("last_working_date", models.DateField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account_number", models.CharField(blank=True, max_length=100)),
                ("bank_branch", models.CharField(blank=True, max_length=100)),
                (
                    "mobile_money_number",
                    models.CharField(
                        blank=True, help_text="MTN/Airtel Money number", max_length=20
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("number_of_dependents", models.IntegerField(default=0)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about employee"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this employee works for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="accounts.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="employees.department",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Direct supervisor/manager",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["employee_number"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Department manager/head",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_departments",
                to="employees.employee",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["company", "employment_status"],
                name="employees_e_company_d090a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["company", "department"], name="employees_e_company_ba5a2a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                fields=("company", "employee_number"),
                name="unique_employee_number_per_company",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                fields=("company", "email"), name="unique_employee_email_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_department_per_company"
            ),
        ),
    ]
