# Generated by Django 6.0 on 2025-12-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["company", "join_date"], name="employees_e_company_8e5f43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["company", "email"], name="employees_e_company_90826c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["company", "employee_number"],
                name="employees_e_company_182361_idx",
            ),
        ),
    ]
