# Generated by Django 6.0.1 on 2026-01-19 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_company_attendance_exceptions_alerts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google_calendar', 'Google Calendar'), ('microsoft_outlook', 'Microsoft Outlook'), ('zoom', 'Zoom Meetings'), ('teams', 'Microsoft Teams'), ('aws_s3', 'AWS S3 Storage')], max_length=50)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('bucket_name', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='accounts.company')),
            ],
            options={
                'unique_together': {('company', 'provider')},
            },
        ),
    ]
