# Generated by Django 6.0.1 on 2026-01-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalintegration',
            options={'verbose_name': 'External Integration', 'verbose_name_plural': 'External Integrations'},
        ),
        migrations.AddField(
            model_name='externalintegration',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='externalintegration',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('unauthorized', 'Unauthorized'), ('error', 'Error')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='externalintegration',
            name='tenant_id',
            field=models.CharField(blank=True, help_text='Required for Microsoft/Azure integrations', max_length=255),
        ),
        migrations.AddField(
            model_name='externalintegration',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalintegration',
            name='client_secret',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='externalintegration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
