# Generated by Django 6.0 on 2025-12-15 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="external_links",
        ),
        migrations.AddField(
            model_name="candidate",
            name="cover_letter",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="source",
            field=models.CharField(
                choices=[
                    ("career_page", "Career Page"),
                    ("linkedin", "LinkedIn"),
                    ("indeed", "Indeed"),
                    ("referral", "Referral"),
                    ("agency", "Agency"),
                    ("other", "Other"),
                ],
                default="career_page",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="IntegrationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("indeed", "Indeed"),
                            ("glassdoor", "Glassdoor"),
                            ("fuzu", "Fuzu"),
                        ],
                        max_length=50,
                    ),
                ),
                ("client_id", models.CharField(blank=True, max_length=255)),
                ("client_secret", models.CharField(blank=True, max_length=255)),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_board_integrations",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "platform")},
            },
        ),
        migrations.CreateModel(
            name="ExternalJobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="ID returned by the external platform", max_length=255
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("status", models.CharField(default="posted", max_length=50)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_posts",
                        to="recruitment.job",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recruitment.integrationsettings",
                    ),
                ),
            ],
        ),
    ]
