# Generated by Django 6.0 on 2025-12-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recruitment",
            "0002_remove_job_external_links_candidate_cover_letter_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationsettings",
            name="access_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="refresh_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
