# Generated by Django 6.0 on 2025-12-19 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_integrationsettings_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The body of the offer letter')),
                ('salary_offered', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='draft', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter', to='recruitment.application')),
            ],
        ),
    ]
