# Generated by Django 6.0 on 2026-01-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_offerletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scheduled_publish_date',
            field=models.DateTimeField(blank=True, help_text='Auto-publish job at this date/time', null=True),
        ),
    ]
