# Generated by Django 6.0.1 on 2026-01-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_job_scheduled_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='external_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='sync_status',
            field=models.CharField(choices=[('none', 'None'), ('synced', 'Synced'), ('failed', 'Failed')], default='none', max_length=50),
        ),
    ]
