# Generated by Django 6.0 on 2026-01-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_interview_external_event_id_interview_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Meeting link or physical address', max_length=255),
        ),
    ]
